### ISSUE TITLE
306.63ms pre tick

### ISSUE THREAD

**Issue by mat41997** [andrei1058/Reporting1058#4]
ss
![2017-02-26 14_54_26-aikar s timings viewer](https://cloud.githubusercontent.com/assets/5884000/23340281/a8268ba6-fc33-11e6-8727-94f3378b9f67.png)
timings
https://timings.aikar.co/?id=c1a551b0ff8f4b19aef58529155d3640#plugins

fix pls.

**Comment by andrei1058** [comment]
The update method is executed at startup only.

**Comment by andrei1058** [comment]
And it isn't 306 per tick
