### ISSUE TITLE
Stai prea mult pentru un shit plugin

### ISSUE THREAD

**Issue by NycuRO** [andrei1058/Reporting1058#5]
Si nu iti merg comenzile pe nukkit pentru ca citeste config.yml si e diferit fata de ala de bukkit.

**Comment by andrei1058** [comment]
In primul rand vezi-ti de treaba. Macar eu nu fur coduri ca tine. Si comenzile merg, nu ma chinui cu nimic in afara de faptul ca nu merge sa pun update-ul corect pe github. Poate esti chior si nu ai vazut ca lipseste clasa atribuita in nukkit.yml

**Comment by NycuRO** [comment]
Cica fur coduri. Coaie gandesti ce spui?

Faci ce vrei.

**Comment by andrei1058** [comment]
Nu tu furai codul de la nu stiu ce world generator ca sa il portezi pe nukkit? Inainte sa te iei de mine, uita-te la tine. Altfel chestiile ti se intorc impotriva. Daca e plugin shit atunci de ce iti pierzi timpul facand un issue care de fapt e doar spam din partea ta?

**Comment by NycuRO** [comment]
De unde am furat ma eu codul de la nu stiu ce world generator ca sa il portez pe nukkit?

Am portat de la NMS la Nukkit. Au API DIFERIT. Esti tampit sau te prefaci? Crezi ca e asa usor sa portezi rahaturile alea de biomes , copaci si tot?
Pune-ti tu capul cu alea.
Si am zis eu ca (,) copiezi? Chiar esti retardat, copile.
E shit pentru ca e foarte usor sa portezi rahatul asta pe nukkit.
Si nu, nu e de la clasa atributa in nukkit.yml. 
Esti prost.

**Comment by NycuRO** [comment]
In plus, iti zisai. Poti sa stergi si nukkit.yml si tot o sa ruleze rahatul ala de plugin fiindca ai config.yml.

**Comment by andrei1058** [comment]
Nu te-am acuzat ca m-ai facut copiator. Te-ai luat de munca mea, deci de mine.
"In plus, iti zisai. Poti sa stergi si nukkit.yml si tot o sa ruleze rahatul ala de plugin fiindca ai config.yml."
Mai citeste odata ce ai scris. Daca nu stii java vezi-ti de php-ul tau. Nu te-a bagat nimeni in seama. Si tot eu sunt prostul.
